default: &default
  adapter: mysql2
  encoding: utf8
  pool: 8
  username: root
  password:

development:
  <<: *default
  database: githubranking

test:
  <<: *default
  database: githubranking_test

production:
  adapter: mysql2
  encoding: utf8
  username: <%= ENV['GITHUB_RANKS_DATABASE_USER'] %>
  password: <%= ENV['GITHUB_RANKS_DATABASE_PASSWORD'] %>
  socket: <%= ENV['GITHUB_RANKS_DATABASE_SOCKET'] %>
  pool: 8
  database: githubranking
