default: &default
  adapter: mysql2
  encoding: utf8
  pool: 8
  username: root
  password:

development:
  <<: *default
  database: github_ranking

test:
  <<: *default
  database: github_ranking_test

production:
  adapter: mysql2
  encoding: utf8
  username: <%= ENV['GITHUBRANKING_DATABASE_USER'] %>
  password: <%= ENV['GITHUBRANKING_DATABASE_PASSWORD'] %>
  socket: <%= ENV['GITHUBRANKING_DATABASE_SOCKET'] %>
  pool: 8
  database: github_ranking
