default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: 8
  username: root
  password:

development:
  <<: *default
  database: github_ranking

test:
  <<: *default
  database: github_ranking_test

production:
  adapter: mysql2
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: <%= ENV['DATABASE_HOST'] %>
  port: <%= ENV['DATABASE_PORT'] %>
  pool: 8
  database: github_ranking
